spring:
  datasource:
        url: jdbc:mariadb://3.14.29.26:3306/db_messenger
        driver-class-name: org.mariadb.jdbc.Driver
        username: messengerUser
        password: dbmessenger1234!@
        
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update 

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false        
   